### ISSUE TITLE
"year" vs "noauthor" styles, variants

### ISSUE THREAD

**Issue by bdarcus** [andras-simonyi/oc-csl-ns#1]
On this:

``` elisp
 (("noauthor" "na")
  ("bare-caps" "bc")
  ("caps" "c")
  ("bare" "b"))
 (("year" "y")
  ("bare" "b"))
```

I think we changed "year" to the more general "noauthor" (aka "suppress author") style in the other processors, so you might just drop "year", at least initially in oc-csl?

Also, I know you said you struggled with some of the variants, but why the "caps" ones on "noauthor"?

Certainly for author-date it will have no impact.

I'm trying to think about for, say, a note style? Am not sure.

FWIW, oc-biblatex currently has no variants for "noauthor", and natbib just "bare".

**Comment by andras-simonyi** [comment]
As for year vs noauthor, they are radically different for a note style. Caps with noauthor: I guess it might make sense for a note style (e.g., if the title is in lowercase), and also for the prefix (?). But anything can be omitted if it helps providing a unified user experience with the processors.

**Comment by bdarcus** [comment]
I don't have super strong opinion on these details, as we're experimenting with a new system. And you raise good points.

Also, my bias is author-date. While I do sometimes need note styles, it's not my primary mode. So I sometimes miss details there.

Is it common to cite a year only in a note style?

I do think if it makes sense in oc-csl, it probably also makes sense in oc-biblatex, given these should be fairly comparable.

E.g. if you think it's a good idea, you could add these to the latter too.

**Comment by bdarcus** [comment]
PS - there are places where it's hard to harmonize across different style classes. This is one example, and @denismaier and I struggled with this one.

In the UI I've been experimenting with, I've used grouping, and group titles, to try to make more clear how the style system works.

![image](https://user-images.githubusercontent.com/1134/128730804-b86bf82c-0dd0-49af-b1fe-8db102161207.png)

So I title "noauthor" "Supress Author", for example.

But not sure that works for note styles?

It might be that the group titles should be configurable based on preferred citation class.

Of course the preview don't, but ideally those are dynamically generated based on the export style, and they don't need to be exact anyway (though the advantage of the pre-cooked preview is can tailor to expose variants that for most data won't be relevant).

**Comment by denismaier** [comment]
IIRC, the reasoning behind "noauthor" vs "year" was that our priority was portability between different classes of citation styles. If we have this item "John, Doe. /A book/. 2020." the variant "noauthor" can be used to render this consistently.

1. In-Text:
a) author-year: "(2020)"
b) author-title: "(/A book/)"

2. Author-title in footnote: "/A book/. 2020."

Here, it's not so much about what information should be rendered, but rather what should be ommitted.

"Year" would be much less portable. That doesn't mean that "year" couldn't be legitimate, in the sense of  "I really need the year here". But that raises another question: How will citeproc-el know where this year is coming from, and how the year has to be formatted? That will have to be hardcoded in the processor as styles contain no information about this.

**Comment by andras-simonyi** [comment]
> "Year" would be much less portable. That doesn't mean that "year" couldn't be legitimate, in the sense of "I really need the year here". But that raises another question: How will citeproc-el know where this year is coming from, and how the year has to be formatted? That will have to be hardcoded in the processor as styles contain no information about this.

Yes, I have raised the same concerns elsewhere. FWIW, the current implementation simply tries to return the part of the rendered citation which corresponds to the "issued" variable.

**Comment by bdarcus** [comment]
I think I'll close this.
