### ISSUE TITLE
Long-term plans?

### ISSUE THREAD

**Issue by bdarcus** [andras-simonyi/oc-csl-ns#3]
Are you thinking to keep this longer-term, and periodically submit patches to the main oc-csl file?

I'm asking because I'm working on a PR for Doom emacs to add org-cite support. So the obvious question is pros and cons of using this rather than the default one (and similar questions on the activate processor).

**Comment by andras-simonyi** [comment]
Well I'm not totally sure what is the best way forward but my current plan is to make a CSL org-cite processor available which is kept in sync with citeproc-el, and the best way to achieve this seems to be distributing it via MELPA.  So I think this will be around long-term, but probably not as a drop-in replacement but as a processor named `oc-csl-ns` or similar, from which hopefully useful changes will percolate to Org's oc-csl.el sooner or later. The whole situation is a bit tricky because this would be basically a fork of oc-csl which is basically a fork of citeproc-org...

**Comment by bdarcus** [comment]
Makes sense.

So I guess if Doom merges the module changes soon, just use oc-csl, and
then switch to oc-csl-ns when it's available on MELPA?

**Comment by andras-simonyi** [comment]
Yes, this seems to be a sensible strategy. BTW, I've forgotten to add that in the long run I'll add the CSL-based activation processor to oc-csl-ns too, I don't really see any good reason to keep it as a separate package.

**Comment by bdarcus** [comment]
> in the long run I'll add the CSL-based activation processor to oc-csl-ns too, I don't really see any good reason to keep it as a separate package.

Good; I strongly agree. Org-cite is modular enough that there really is no trade-off.

And you may remember Nicolas expressed interest in adding that functionality to oc-csl.

**Comment by bdarcus** [comment]
Just FYI @tecosaur.

**Comment by tecosaur** [comment]
Oh Andras, if you get push access to Org for oc-csl (which I have a feeling Bastien & Nicolas would be happy to give you), you could keep the elpa-devel / rolling release version of org in sync with citeproc-el melpa. Just mentioning this in case you haven't considered this as an option.

**Comment by bdarcus** [comment]
> Oh Andras, if you get push access to Org for oc-csl (which I have a feeling Bastien & Nicolas would be happy to give you), you could keep the elpa-devel / rolling release version of org in sync with citeproc-el melpa. Just mentioning this in case you haven't considered this as an option.

This would be ideal, so this just becomes a development repo, but the main distribution is via the org repo, but there's little or no lag.

**Comment by andras-simonyi** [comment]
@tecosaur  wrote:

> Oh Andras, if you get push access to Org for oc-csl (which I have a feeling Bastien & Nicolas would be happy to give you), you could keep the elpa-devel / rolling release version of org in sync with citeproc-el melpa. Just mentioning this in case you haven't considered this as an option.

Thanks for the suggestion and sorry for the late reaction, I was not aware that there is a rolling Org release as well on ELPA. Will try to raise the issue on the Org mailing list.
